#!/bin/bash

if [[ $1 == "doc" ]]
then
    # Build documentation.
    cd doc
    make clean
    make html

elif [[ $1 == 'mongo' ]]
then
    # Start MongoDB server.
    ./mongodb/bin/mongod --dbpath mongodb/data

elif [[ $1 == 'test' ]]
then
    # Run tests
    source env/dev/bin/activate
    nosetests

elif [[ $1 == "setup" ]]
then
    if [[ $2 == 'nltk' ]]
    then
        # Install NLTK data.

        # Tokenizing and lemmatization.
        python -m nltk.downloader punkt
        python -m nltk.downloader wordnet
        python -m nltk.downloader stopwords

        # Named Entity Recognition
        python -m nltk.downloader words
        # Not yet Python 3 ready:
        #python -m nltk.downloader maxent_treebank_pos_tagger
        #python -m nltk.downloader maxent_ne_chunker

        # Installing Python 3 ready alternative data
        curl -o ~/nltk_data/chunkers/maxent_ne_chunker.zip 'https://github.com/jskda/nltk_data/blob/gh-pages-repickle/packages/chunkers/maxent_ne_chunker.zip'
        unzip ~/nltk_data/chunkers/maxent_ne_chunker.zip
        curl -o ~/nltk_data/taggers/maxent_treebank_pos_tagger.zip 'https://github.com/jskda/nltk_data/blob/gh-pages-repickle/packages/taggers/maxent_treebank_pos_tagger.zip'
        unzip ~/nltk_data/taggers/maxent_treebank_pos_tagger.zip

    elif [[ $2 == 'mongo' ]]
    then
        # Setup MongoDB.
        curl -o mongodb.tgz 'http://fastdl.mongodb.org/osx/mongodb-osx-x86_64-2.4.5.tgz'
        mkdir mongodb
        tar --extract --file=mongodb.tgz --strip-components=1 --directory=mongodb
        rm mongodb.tgz
        mkdir mongodb/data
    fi
fi

