#!/bin/bash

echo -e "\n\n\n"
echo -e "$(tput setaf 3)Loading default sources to the database. This may take awhile...$(tput sgr0)"
echo -e "\n\n\n"

dev-env/bin/python -c 'from web.app import app
from database.datastore import init_db, init_model
from flask.ext.sqlalchemy import SQLAlchemy

db = SQLAlchemy(app)

init_db(db)
init_model(db.Model)

import web.models

import core.membrane.collector as c

c.load_sources_from_file()'
