"""empty message

Revision ID: 33a60e4c14c
Revises: 37d55fb58e3
Create Date: 2014-04-24 14:41:59.830157

"""

# revision identifiers, used by Alembic.
revision = '33a60e4c14c'
down_revision = '37d55fb58e3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concept', sa.Column('commonness', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concept', 'commonness')
    ### end Alembic commands ###
