"""empty message

Revision ID: 37d55fb58e3
Revises: 4069b1183ed
Create Date: 2014-04-07 17:41:39.702508

"""

# revision identifiers, used by Alembic.
revision = '37d55fb58e3'
down_revision = '4069b1183ed'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('feed_id', sa.Integer(), nullable=True))
    op.add_column('feed', sa.Column('source_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'feed', ['ext_url'])
    op.add_column('source', sa.Column('icon', sa.String(length=255), nullable=True))
    op.drop_column('source', 'errors')
    op.drop_column('source', 'updated_at')
    op.drop_column('source', 'updating')
    op.drop_column('source', 'ext_url')
    op.create_unique_constraint(None, 'source', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'source')
    op.add_column('source', sa.Column('ext_url', sa.VARCHAR(), nullable=True))
    op.add_column('source', sa.Column('updating', sa.BOOLEAN(), nullable=True))
    op.add_column('source', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('source', sa.Column('errors', sa.INTEGER(), nullable=True))
    op.drop_column('source', 'icon')
    op.drop_constraint(None, 'feed')
    op.drop_column('feed', 'source_id')
    op.drop_column('article', 'feed_id')
    ### end Alembic commands ###
