"""empty message

Revision ID: 4069b1183ed
Revises: None
Create Date: 2014-04-07 01:16:40.210443

"""

# revision identifiers, used by Alembic.
revision = '4069b1183ed'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('source', sa.Column('updating', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'updating')
    op.drop_column('source', 'updated_at')
    ### end Alembic commands ###
