"""empty message

Revision ID: 47f524fef35
Revises: 33a60e4c14c
Create Date: 2014-12-15 02:30:51.105743

"""

# revision identifiers, used by Alembic.
revision = '47f524fef35'
down_revision = '33a60e4c14c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ignore', sa.Boolean(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('ignore')

    ### end Alembic commands ###
